apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  dex:
    openShiftOAuth: true
  rbac:
    policy: |
      g, system:cluster-admins, role:admin
      g, cluster-admins, role:admin
    scopes: '[groups]'
    defaultPolicy: "role:admin"
  server:
    insecure: true
    route:
      enabled: true
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
  resourceCustomizations: |
    route.openshift.io/Route:
      ignoreDifferences: |
        jsonPointers:
        - /spec/host
    apps/Deployment:
      ignoreDifferences: |
        jsonPointers:
        - /spec/template/spec/containers/0/image
    apps.openshift.io/DeploymentConfig:
      ignoreDifferences: |
        jsonPointers:
        - /spec/template/spec/containers/0/image
