apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nodejs-welcome
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: demo-gitops-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: nodejs-welcome-{{name}}
    spec:
      project: default
      source:
        repoURL: https://github.com/sa-ne/acm-argocd-application.git
        targetRevision: main
        path: gitops/manifests/nodejs-welcome/base
      destination:
        namespace: welcome
        server: "{{server}}" 
      syncPolicy:
        automated:
          selfHeal: false